version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - OPENAI_API_KEY='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'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
